### ISSUE TITLE
Link to personal blog

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec-site#5]
This blog post gives some interesting information about megaparsec https://mrkkrp.github.io/posts/latest-additions-to-megaparsec.html

but the megaparsec website does not link to here so it's hard to find

**Comment by mrkkrp** [comment]
Perhaps we could add this to readme?

**Comment by flip111** [comment]
Might be even better yeah

**Comment by mrkkrp** [comment]
Done: mrkkrp/megaparsec@27c4141.
